slug: rabbi-elimelech-biderman-hrh-tz-r-alymlch-bydrmn-shlyt-a
enabled: true
sources:
- type: existing_feed
  feed_url: https://anchor.fm/s/d6ba26fc/podcast/rss
  delivery_mode: linked
  start_date: '1900-01-01'
podcast:
  title: Rabbi Elimelech Biderman הרה"צ ר' אלימלך בידרמן שליט"א
  owner_name: Torah Pod
  owner_email: torahyoupod@gmail.com
  author: הרה"צ ר' אלימלך בידרמן שליט"א
  description: To sign up for the short daily clips from Reb Meilech, for info on
    how to get the weekly booklets or audios to your email and other questions, send
    a whatsapp message to +1 845 293 2166To sign up for the short daily clips from
    Reb Meilech, for info on how to get the weekly booklets or audios to your email
    and other questions, send a whatsapp message to +1 845 293 2166 שיעורים של הרה"צ
    ר' אלימלך בידרמן שליט"א
  language: he
  category: Religion & Spirituality
  subcategory: Judaism
  explicit: 'no'
  copyright: Copyright and other rights remain with the respective rights holders.
  website_url: https://anchor.fm/rabbi-elimelech
  feed_url: https://anchor.fm/s/d6ba26fc/podcast/rss
  artwork_path: shows/rabbi-elimelech-biderman-hrh-tz-r-alymlch-bydrmn-shlyt-a/assets/podcast-cover.png
  artwork_url: https://torah-pod.pages.dev/rabbi-elimelech-biderman-hrh-tz-r-alymlch-bydrmn-shlyt-a/assets/podcast-cover.png
r2:
  prefix: rabbi-elimelech-biderman-hrh-tz-r-alymlch-bydrmn-shlyt-a
onboarding:
  issue: 2
